[package]
edition = "2021"
name = "modify"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.47"
syn = { version = "1.0.103", features = ["full"] }
